services:
  nginx:
    image: evild/alpine-nginx:stable-openssl
    container_name: respund_nginx
    volumes:
      - ./:/var/www/html/:ro
      - ./docker/nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - 8011:80
    links:
      - php
    depends_on:
      - db
      - php
  php:
    build: docker/php
    container_name: respund_php
    #  "${UID}:${GID}" @SEE .env
    user: "${UID}:${GID}"
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    environment:
      - DB_TEST_DATABASE=app_test
      - DB_DATABASE=app
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=password

  db:
    image: mariadb:latest
    container_name: respund_db
    volumes:
      - ./.mysql:/var/lib/mysql
      - ./init/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MARIADB_ROOT_PASSWORD=password
volumes:
  db-data:
    driver: local

networks:
  default:
    name: dev1
    external: true

